In [1]:
import pandas as pd

elo = pd.read_csv("../data/raw/elo_ratings/eloratings.csv")

elo.head()

         date      team  rating  change
0  1872-11-30   England  2003.0       3
1  1872-11-30  Scotland  1997.0      -3
2  1873-03-08   England  2014.0      11
3  1873-03-08  Scotland  1986.0     -11
4  1874-03-07   England  2006.0      -8

In [2]:
print("Shape:")
print(elo.shape)

print("\nColumns:")
print(elo.columns.tolist())

print("\nData Types:")
elo.info()

Shape:
(6678, 4)

Columns:
['date', 'team', 'rating', 'change']

Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 6678 entries, 0 to 6677
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    6678 non-null   str
 1   team    6678 non-null   str
 2   rating  6647 non-null   float64
 3   change  6678 non-null   int64
dtypes: float64(1), int64(1), str(2)
memory usage: 208.8 KB

In [15]:
print("\nMissing Values:")
display(elo.isnull().sum())

print("\nDuplicate Rows:")
print(elo.duplicated().sum())

Missing Values:

date       0
team       0
rating    31
change     0
dtype: int64

Duplicate Rows:
0

In [5]:
elo.describe(include="all")

              date     team       rating       change
count         6678     6678  6647.000000  6678.000000
unique         419      270          NaN          NaN
top     12/13/2025  Ireland          NaN          NaN
freq           244       60          NaN          NaN
mean           NaN      NaN  1490.960734     0.000000
std            NaN      NaN   299.252797    15.319033
min            NaN      NaN     0.000000   -86.000000
25%            NaN      NaN  1275.000000    -9.000000
50%            NaN      NaN  1511.000000     0.000000
75%            NaN      NaN  1712.000000     9.000000
max            NaN      NaN  2171.000000    86.000000

In [6]:
for col in elo.columns:
    print("=" * 60)
    print(col)
    print(elo[col].head())

============================================================
date
0    1872-11-30
1    1872-11-30
2    1873-03-08
3    1873-03-08
4    1874-03-07
Name: date, dtype: str
============================================================
team
0     England
1    Scotland
2     England
3    Scotland
4     England
Name: team, dtype: str
============================================================
rating
0    2003.0
1    1997.0
2    2014.0
3    1986.0
4    2006.0
Name: rating, dtype: float64
============================================================
change
0     3
1    -3
2    11
3   -11
4    -8
Name: change, dtype: int64

In [8]:
elo.columns.tolist()

['date', 'team', 'rating', 'change']

In [9]:
elo.shape

(6678, 4)

In [11]:
elo.isnull().sum()

date       0
team       0
rating    31
change     0
dtype: int64

In [12]:
elo.head()

         date      team  rating  change
0  1872-11-30   England  2003.0       3
1  1872-11-30  Scotland  1997.0      -3
2  1873-03-08   England  2014.0      11
3  1873-03-08  Scotland  1986.0     -11
4  1874-03-07   England  2006.0      -8

In [13]:
elo.duplicated().sum()

np.int64(0)