In [2]:
import pandas as pd

rankings = pd.read_csv("../data/raw/fifa_rankings/fifa_rankings.csv")

rankings.head()

,rank,country_abrv,total_points,previous_points,rank_change,confederation,rank_date,team
0,1,GER,57.0,0.0,0,UEFA,1992-12-31,Germany
1,96,SYR,11.0,0.0,0,AFC,1992-12-31,Syria
2,97,BFA,11.0,0.0,0,CAF,1992-12-31,Burkina Faso
3,99,LVA,10.0,0.0,0,UEFA,1992-12-31,Latvia
4,100,BDI,10.0,0.0,0,CAF,1992-12-31,Burundi

In [3]:
print("Shape:")
print(rankings.shape)

print("\nColumns:")
print(rankings.columns.tolist())

print("\nData Types:")
rankings.info()

Shape:
(63899, 8)

Columns:
['rank', 'country_abrv', 'total_points', 'previous_points', 'rank_change', 'confederation', 'rank_date', 'team']

Data Types:
<class 'pandas.DataFrame'>
RangeIndex: 63899 entries, 0 to 63898
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             63899 non-null  int64
 1   country_abrv     63899 non-null  str
 2   total_points     63899 non-null  float64
 3   previous_points  63899 non-null  float64
 4   rank_change      63899 non-null  int64
 5   confederation    63899 non-null  str
 6   rank_date        63899 non-null  str
 7   team             63899 non-null  str
dtypes: float64(2), int64(2), str(4)
memory usage: 3.9 MB

In [4]:
print("\nMissing Values:")
display(rankings.isnull().sum())

print("\nDuplicate Rows:")
print(rankings.duplicated().sum())

Missing Values:

rank               0
country_abrv       0
total_points       0
previous_points    0
rank_change        0
confederation      0
rank_date          0
team               0
dtype: int64

Duplicate Rows:
0

In [6]:
rankings.describe(include="all")

,rank,country_abrv,total_points,previous_points,rank_change,confederation,rank_date,team
count,63899.000000,63899,63899.000000,63899.000000,63899.000000,63899,63899,63899
unique,NaN,211,NaN,NaN,NaN,6,322,211
top,NaN,GER,NaN,NaN,NaN,UEFA,2018-07-01,Germany
freq,NaN,322,NaN,NaN,NaN,16760,211,322
mean,100.196638,NaN,442.487205,441.103756,0.005133,NaN,NaN,NaN
std,58.055432,NaN,409.102046,409.325049,5.660956,NaN,NaN,NaN
min,1.000000,NaN,1.000000,0.000000,-92.000000,NaN,NaN,NaN
25%,50.000000,NaN,88.000000,86.000000,-1.000000,NaN,NaN,NaN
50%,100.000000,NaN,347.000000,345.000000,0.000000,NaN,NaN,NaN
75%,149.000000,NaN,641.000000,640.000000,2.000000,NaN,NaN,NaN
max,211.000000,NaN,2172.000000,2187.000000,199.000000,NaN,NaN,NaN

In [7]:
for col in rankings.columns:
    print("=" * 60)
    print(col)
    print(rankings[col].head())

============================================================
rank
0      1
1     96
2     97
3     99
4    100
Name: rank, dtype: int64
============================================================
country_abrv
0    GER
1    SYR
2    BFA
3    LVA
4    BDI
Name: country_abrv, dtype: str
============================================================
total_points
0    57.0
1    11.0
2    11.0
3    10.0
4    10.0
Name: total_points, dtype: float64
============================================================
previous_points
0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: previous_points, dtype: float64
============================================================
rank_change
0    0
1    0
2    0
3    0
4    0
Name: rank_change, dtype: int64
============================================================
confederation
0    UEFA
1     AFC
2     CAF
3    UEFA
4     CAF
Name: confederation, dtype: str
============================================================
rank_date
0    1992-12-31
1    1992-12-31
2    1992-12-31
3    1992-12-31
4    1992-12-31
Name: rank_date, dtype: str
============================================================
team
0         Germany
1           Syria
2    Burkina Faso
3          Latvia
4         Burundi
Name: team, dtype: str

In [8]:
rankings.columns.tolist()

['rank',
 'country_abrv',
 'total_points',
 'previous_points',
 'rank_change',
 'confederation',
 'rank_date',
 'team']

In [9]:
rankings.shape

(63899, 8)

In [10]:
rankings.isnull().sum()

rank               0
country_abrv       0
total_points       0
previous_points    0
rank_change        0
confederation      0
rank_date          0
team               0
dtype: int64

In [12]:
rankings.duplicated().sum()

np.int64(0)

In [13]:
rankings.head()

,rank,country_abrv,total_points,previous_points,rank_change,confederation,rank_date,team
0,1,GER,57.0,0.0,0,UEFA,1992-12-31,Germany
1,96,SYR,11.0,0.0,0,AFC,1992-12-31,Syria
2,97,BFA,11.0,0.0,0,CAF,1992-12-31,Burkina Faso
3,99,LVA,10.0,0.0,0,UEFA,1992-12-31,Latvia
4,100,BDI,10.0,0.0,0,CAF,1992-12-31,Burundi

In [14]:
from pathlib import Path
import pandas as pd

BASE_DIR = Path.cwd().parent

cleaned = pd.read_csv(
    BASE_DIR / "data" / "interim" / "rankings_clean.csv"
)

print(cleaned.shape)
display(cleaned.head())
cleaned.info()

(63899, 8)

,rank,country_abrv,total_points,previous_points,rank_change,confederation,rank_date,team
0,1,GER,57.0,0.0,0,UEFA,1992-12-31,Germany
1,96,SYR,11.0,0.0,0,AFC,1992-12-31,Syria
2,97,BFA,11.0,0.0,0,CAF,1992-12-31,Burkina Faso
3,99,LVA,10.0,0.0,0,UEFA,1992-12-31,Latvia
4,100,BDI,10.0,0.0,0,CAF,1992-12-31,Burundi

<class 'pandas.DataFrame'>
RangeIndex: 63899 entries, 0 to 63898
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   rank             63899 non-null  int64
 1   country_abrv     63899 non-null  str
 2   total_points     63899 non-null  float64
 3   previous_points  63899 non-null  float64
 4   rank_change      63899 non-null  int64
 5   confederation    63899 non-null  str
 6   rank_date        63899 non-null  str
 7   team             63899 non-null  str
dtypes: float64(2), int64(2), str(4)
memory usage: 3.9 MB